disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - multiple_closures_with_trailing_closure
  - implicit_optional_initialization

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - redundant_nil_coalescing

included:
  - Sources
  - Tests

excluded:
  - .build

line_length: 160
function_body_length: 100
type_body_length: 500
file_length: 800

identifier_name:
  min_length: 3
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - t1
    - t2
    - s1
    - s2
    - id
